# ParticleX Configuration
# https://github.com/theme-particlex/hexo-theme-particlex

# Avatar image
avatar: https://img.zmal.top/avatar.png

arrow: https://img.zmal.top/20250905/Arrow.175qf571ue.ico

# Home page background image
background:
  - https://img.zmal.top/20250905/brackgroud.86tzx1jeol.jpg

# Loading image
loading: https://img.zmal.top/20250905/loading.7i0qd0vvo5.gif

# Optional colors for category and tag
colors:
    - "#ffa2c4"
    - "#00bcd4"
    - "#03a9f4"
    - "#00a596"
    - "#ff7d73"
    - "#f5bcd0"
    - "#aee8fe"
    - "#66CCFF"
    - "#39C5BB"

# ParticleX theme icon is adopts the Font Awesome 6
# https://fontawesome.com

#文字点击特效
span:
  enable: true
#顶部进度条
TopIndex:
  enable: true
# 背景粒子特效
Background_particles:
  enable: true

# Main menu navigation
menu:
  Home:
    name: house
    theme: solid
    link: /
  About:
    name: id-card
    theme: solid
    link: /about
  Archives:
    name: box-archive
    theme: solid
    link: /archives
  #Categories:
  #    name: bookmark
  #    theme: solid
  #    link: /categories
  Tags:
    name: tags
    theme: solid
    link: /tags

# Side info card
card:
  enable: true
  description: |
    总能在平凡的日子里发现无数温暖的惊喜
  iconLinks:
  friendLinks:
    Github: https://github.com/kmizmal

# Footer info
footer:
  # 底部起始时间yyyy
  since: 2022
  # Customize the server domain name ICP
  ICP:
    enable: true
    code: 萌ICP备20250124号
    link: https://icp.gov.moe/?keyword=20250124

  visitors:
    enable: true
# Polyfill
# https://polyfill.io
polyfill:
  enable: true
  features:
    - default

# https://prismjs.com/examples.html
prismjs:
  enable: true
  theme: prism-tomorrow
  lineNumbers: true

# https://highlightjs.org/
highlight:
  enable: false

# KaTeX math rendering
math:
  enable: false

# Image preview
preview:
  enable: true

# Article encryption
crypto:
  enable: false

# Search
search:
  enable: true

# giscus
# https://github.com/giscus/giscus
giscus:
  enable: false
  src: https://giscus.app/client.js
  repo:
  repoID:
  category:
  categoryID:
  mapping: pathname
  strict: 0
  reactionsEnabled: 1
  emitMetadata: 0
  inputPosition: bottom
  theme: preferred_color_scheme
  lang:

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
  enable: false
  clientID: # Default ClientID
  clientSecret: # Default ClientSecret
  repo: # The name of repository of store comments
  owner: # GitHub repo owner
  admin: # GitHub repo owner and collaborators, only these guys can initialize github issues
  language: # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available
  proxy: # CORS proxy

# Waline
# https://github.com/walinejs/waline
waline:
  enable: false
  serverURL: # Waline server address url, you should set this to your own link
  locale: # Locale: https://waline.js.org/guide/client/i18n.html#locale-option
  commentCount: true # If false, comment count will only be displayed in post page, not in home page
  pageview: false # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`
  emoji: # Custom emoji
    - https://unpkg.com/@waline/emojis@1.2.0/weibo
    - https://unpkg.com/@waline/emojis@1.2.0/alus
    - https://unpkg.com/@waline/emojis@1.2.0/bilibili
    - https://unpkg.com/@waline/emojis@1.2.0/qq
    - https://unpkg.com/@waline/emojis@1.2.0/tieba
    - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
  meta: # Comment information, valid meta are nick, mail and link
    - nick
    - mail
    - link
  requiredMeta: # Set required meta field, e.g.: [nick] | [nick, mail]
    - nick
  lang: # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
  wordLimit: 0 # Word limit, no limit when setting to 0
  login: enable # Whether enable login, can choose from 'enable', 'disable' and 'force'
  pageSize: 10 # Comment per page

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
  enable: true
  envID: https://twikoo.zmal.top
  region:
  path: location.pathname
  lang: zh-cn
